[package]
name = "smoldb"
version = "0.1.0"
edition = "2021"
authors = ["Evan Fleming"]
license = "MIT"
description = "A naive distributed sql database written in Rust entirely for learning purposes."
repository = "https://github.com/oldmanfleming/smoldb"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
